name: test-dispatch
on:
  workflow_dispatch:
    inputs:
      bump:
        description: test
        required: false
        type: choice
        options:
          - patch
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: echo ok
